# Generated by Django 5.0.6 on 2024-06-27 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_promotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_room_reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.promotion'),
        ),
        migrations.AddField(
            model_name='room',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.promotion'),
        ),
    ]
