# Generated by Django 5.0.6 on 2024-07-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_guest_options_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='has_used_promotion',
            field=models.BooleanField(default=False),
        ),
    ]
